export const fontSizes = {
  screenHeader: '24px',
  closeIcon: '24px',
  subheading: '22px',
  arrowFlowTitle: '24px',
  arrowFlowDescription: '16px',
  inputTextLabel: '16px',
  cardText: '14px',
  sectionTitle: '18px',
  sectionText: '14px',
  buttonText: '18px',
  ProfileTitle: '18px',
  ProfileContent: '14px',
  homelessUserDetails: '16px',
};
